ExpWithEF/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using ExpWithEF.Models;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ExpWithEF.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public RolesController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public IActionResult Index() => View(roleManager.Roles.ToList());

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Required]string name)
        {
            if(ModelState.IsValid)
            {
                var result = await roleManager.CreateAsync(new IdentityRole(name));
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddError(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string Id)
        {
            var role = await roleManager.FindByIdAsync(Id);
            if(role != null)
            {
                var result = await roleManager.DeleteAsync(role);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddError(result);
                }
            }
            ModelState.AddModelError("", "Role not found");
            return View("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if(user != null)
            {
                var userRoles = await userManager.GetRolesAsync(user);
                var allRoles = roleManager.Roles.ToList();
                ChangeRoleModel model = new ChangeRoleModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    UserRoles = userRoles.ToList(),
                    AllRoles = allRoles
                };
                return View(model);
            }
            ModelState.AddModelError("", "User not found");
            return View("Index", "Admin");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, List<string> roles)
        {
            User user = await userManager.FindByIdAsync(id);
            if(user != null)
            {
                var userRoles = await userManager.GetRolesAsync(user);

                var addedRoles = roles.Except(userRoles);

                var removedRoles = userRoles.Except(roles);

                await userManager.AddToRolesAsync(user, addedRoles);

                await userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index", "Admin");
            }
            ModelState.AddModelError("", "User not found");
            return View();
        }

        public void AddError(IdentityResult result)
        {
            foreach(var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

ExpWithEF/Views/Admin/EditOrder.cshtml
@model EditOrderModel

<div class="panel-body bg-primary"><h3>Edit Order</h3></div><br />
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="EditOrder" method="post">
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" readonly />
        <span asp-validation-for="OrderId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UserId"></label>
        <input asp-for="UserId" class="form-control" readonly/>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UserName"></label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CarId">Car Id</label>
        <select class="form-control" asp-for="CarId">
            
            @foreach(Car car in Model.Cars)
            {
                <option value="@car.Id">Company: @car.company, Model: @car.model, Color: @car.color, Price: @car.price, Id: @car.Id</option>
            }
        </select>
        <span asp-validation-for="CarId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Index" class="btn btn-danger">Cancel</a>
</form>

ExpWithEF/Views/Admin/Index.cshtml
@model IEnumerable<User>

<div class="bg-primary panel-body"><h3>Users</h3></div>
<table class="table table-bordered table-condensed table-striped">
    <tr><th>ID</th><th>Nickname</th><th>Email</th></tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3" class="text-center">No Users Accounts</td></tr>
    }
    else
    {
        foreach (User user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <form asp-action="Delete" method="post" asp-route-id="@user.Id">
                        <a class="btn btn-primary" asp-route-id="@user.Id" asp-action="UserOrders">Orders</a>
                        <a class="btn btn-warning" asp-route-id="@user.Id" asp-controller="Roles" asp-action="Edit">Access rights</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>

        }
    }
</table>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Cars</a>
<a class="btn btn-primary" asp-controller="Home" asp-action="AllOrders">All Orders</a>

ExpWithEF/Views/Admin/UserOrders.cshtml
@model IEnumerable<Order>

<div class="bg-primary panel-body"><h3>Orders</h3></div>
<table class="table table-bordered table-condensed table-striped">
    <tr><th>Order ID</th><th>User ID</th><th>Name</th><th>Phone</th><th>Address</th><th>Car ID</th></tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="6" class="text-center">No orders</td></tr>
    }
    else
    {
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.OrderId</td>
                <td>@order.UserId</td>
                <td>@order.UserName</td>
                <td>@order.Phone</td>
                <td>@order.Address</td>
                <td>@order.Car.Id</td>
                <td>
                    <form asp-action="DeleteOrder" asp-route-id="@order.OrderId" method="post">
                        <a class="btn btn-warning" asp-route-id="@order.OrderId" asp-action="EditOrder">Edit</a>
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>
<a class="btn btn-danger" asp-action="Index">Cancel</a>